"""25 fictional Anyang merchants, ported 1:1 from
LocalPayiOS/LocalPay/Data/Dummy/DummyMerchantSeed.swift.

Kept as plain Python literals so any change in the iOS seed can be re-applied
here without pulling in Swift tooling. Every merchant here corresponds to the
same iOS `Merchant.id` (e.g. "m-001"), so iOS Dummy → Server Remote swap keeps
the same IDs.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _days_ago(n: int) -> datetime:
    return _now() - timedelta(days=n)


def build_seed_merchants() -> List[Dict[str, Any]]:
    """Return the seed list. Called at seed time so timestamps are fresh."""
    return [
        {
            "id": "m-001",
            "name": "안양중앙시장 행복정육점",
            "category": "food",
            "latitude": 37.3946, "longitude": 126.9235,
            "address": "경기 안양시 만안구 만안로 232 안양중앙시장 내",
            "road_address": "경기 안양시 만안구 만안로 232",
            "phone": "031-441-1101",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "onnuriCard", "localCurrency", "card"],
            "products": ["삼겹살", "목살", "한우 등심", "선물세트", "양념갈비"],
            "business_hours": {"summary": "매일 09:00 - 20:00", "closedNote": "둘째·넷째 일요일 휴무"},
            "rating": 4.7, "review_count": 128,
            "market_name": "안양중앙시장",
            "description": "3대째 이어온 정육점. 온누리·안양사랑페이 모두 사용 가능합니다.",
            "last_verified_at": _days_ago(1),
            "reviews": [
                {"user_name": "안양민준", "rating": 5, "content": "삼겹살 구매했는데 디지털 온누리 결제 잘 됩니다. 고기 신선해요.", "created_at": _days_ago(3), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "삼겹살"},
                {"user_name": "평촌맘", "rating": 4, "content": "지류 온누리도 받아주세요. 친절하십니다.", "created_at": _days_ago(10), "payment_type": "onnuriPaper", "payment_verified": True, "purchased_product": "양념갈비"},
                {"user_name": "안양토박이", "rating": 5, "content": "안양사랑페이 7% 할인 받으니 훨씬 이득이네요.", "created_at": _days_ago(20), "payment_type": "localCurrency", "payment_verified": True, "purchased_product": "한우 등심"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(0), "note": "삼겹살 500g"},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(3), "note": "한우 등심"},
                {"payment_type": "onnuriPaper", "succeeded_at": _days_ago(7), "note": None},
            ],
        },
        {
            "id": "m-002",
            "name": "중앙시장 청년반찬",
            "category": "food",
            "latitude": 37.3951, "longitude": 126.9240,
            "address": "경기 안양시 만안구 만안로 234 안양중앙시장 청년몰",
            "road_address": "경기 안양시 만안구 만안로 234",
            "phone": "031-441-2020",
            "supports_onnuri": True, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["onnuriDigital", "onnuriCard", "card"],
            "products": ["멸치볶음", "장조림", "김치", "제육볶음", "명란젓"],
            "business_hours": {"summary": "화-일 10:00 - 20:00", "closedNote": "월요일 휴무"},
            "rating": 4.5, "review_count": 62,
            "market_name": "안양중앙시장",
            "description": "청년몰의 인기 반찬가게. 소포장 반찬 종류가 많습니다.",
            "last_verified_at": _days_ago(5),
            "reviews": [
                {"user_name": "미영", "rating": 5, "content": "온누리 카드형으로 결제됨. 반찬 맛있어요!", "created_at": _days_ago(2), "payment_type": "onnuriCard", "payment_verified": True, "purchased_product": "장조림"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriCard", "succeeded_at": _days_ago(1), "note": "반찬 3종"},
            ],
        },
        {
            "id": "m-003",
            "name": "범계할머니손칼국수",
            "category": "restaurant",
            "latitude": 37.3902, "longitude": 126.9769,
            "address": "경기 안양시 동안구 시민대로 175",
            "road_address": "경기 안양시 동안구 시민대로 175",
            "phone": "031-386-4455",
            "supports_onnuri": False, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["localCurrency", "card"],
            "products": ["손칼국수", "만두국", "수육", "김치전"],
            "business_hours": {"summary": "매일 11:00 - 21:00", "closedNote": None},
            "rating": 4.6, "review_count": 214,
            "market_name": None,
            "description": "20년 전통 손칼국수집. 안양사랑페이 결제 가능.",
            "last_verified_at": _days_ago(2),
            "reviews": [
                {"user_name": "혜정", "rating": 5, "content": "안양사랑페이 결제되고 국물 진해요.", "created_at": _days_ago(4), "payment_type": "localCurrency", "payment_verified": True, "purchased_product": "손칼국수"},
            ],
            "recent_payments": [
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(1), "note": None},
            ],
        },
        {
            "id": "m-004",
            "name": "평촌우리약국",
            "category": "pharmacy",
            "latitude": 37.3918, "longitude": 126.9690,
            "address": "경기 안양시 동안구 평촌대로 132",
            "road_address": "경기 안양시 동안구 평촌대로 132",
            "phone": "031-381-7788",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "localCurrency", "card"],
            "products": ["타이레놀", "지사제", "종합감기약", "밴드", "비타민"],
            "business_hours": {"summary": "월-금 09:00 - 21:00 / 토 09:00 - 18:00", "closedNote": "일요일·공휴일 휴무"},
            "rating": 4.4, "review_count": 47,
            "market_name": None,
            "description": "친절 상담이 좋은 동네 약국.",
            "last_verified_at": _days_ago(3),
            "reviews": [
                {"user_name": "재훈", "rating": 4, "content": "종합감기약 사면서 온누리 디지털 결제 잘 됐어요.", "created_at": _days_ago(6), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "종합감기약"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(2), "note": None},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(8), "note": None},
            ],
        },
        {
            "id": "m-005",
            "name": "안양착한카페",
            "category": "cafe",
            "latitude": 37.3970, "longitude": 126.9270,
            "address": "경기 안양시 만안구 만안로 210",
            "road_address": "경기 안양시 만안구 만안로 210",
            "phone": "031-441-3300",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "localCurrency", "card"],
            "products": ["아메리카노", "카페라떼", "크로플", "수제청 에이드"],
            "business_hours": {"summary": "매일 08:00 - 22:00", "closedNote": None},
            "rating": 4.8, "review_count": 340,
            "market_name": None,
            "description": "안양의 대표 착한가격 카페. 온누리·지역화폐 모두 사용 가능.",
            "last_verified_at": _days_ago(1),
            "reviews": [
                {"user_name": "지수", "rating": 5, "content": "아메리카노 2500원인데 온누리도 됨. 무조건 옴.", "created_at": _days_ago(2), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "아메리카노"},
                {"user_name": "은비", "rating": 5, "content": "안양사랑페이로 결제 잘 되고 사장님 친절해요.", "created_at": _days_ago(9), "payment_type": "localCurrency", "payment_verified": True, "purchased_product": "카페라떼"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(0), "note": "아메리카노 2잔"},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(5), "note": None},
            ],
        },
        {
            "id": "m-006",
            "name": "평촌생활마트",
            "category": "mart",
            "latitude": 37.3892, "longitude": 126.9660,
            "address": "경기 안양시 동안구 평촌대로 88",
            "road_address": "경기 안양시 동안구 평촌대로 88",
            "phone": "031-386-1010",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriCard", "localCurrency", "card", "qr"],
            "products": ["즉석밥", "라면", "우유", "계란", "세제"],
            "business_hours": {"summary": "매일 08:00 - 23:00", "closedNote": None},
            "rating": 4.3, "review_count": 89,
            "market_name": None,
            "description": "동네 생활 필수품 마트.",
            "last_verified_at": _days_ago(4),
            "reviews": [
                {"user_name": "서연", "rating": 4, "content": "온누리·지역화폐 다 되니 편해요.", "created_at": _days_ago(7), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "즉석밥"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(2), "note": None},
            ],
        },
        {
            "id": "m-007",
            "name": "인덕원분식",
            "category": "restaurant",
            "latitude": 37.4014, "longitude": 126.9782,
            "address": "경기 안양시 동안구 관평로 289",
            "road_address": "경기 안양시 동안구 관평로 289",
            "phone": "031-421-1122",
            "supports_onnuri": True, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "card"],
            "products": ["떡볶이", "김밥", "라볶이", "튀김"],
            "business_hours": {"summary": "화-일 11:00 - 21:00", "closedNote": "월요일 휴무"},
            "rating": 4.5, "review_count": 156,
            "market_name": None,
            "description": "인덕원 20년 분식집.",
            "last_verified_at": _days_ago(6),
            "reviews": [
                {"user_name": "다현", "rating": 5, "content": "지류 온누리 받아주는 몇 안 되는 분식집!", "created_at": _days_ago(4), "payment_type": "onnuriPaper", "payment_verified": True, "purchased_product": "떡볶이"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriPaper", "succeeded_at": _days_ago(1), "note": None},
            ],
        },
        {
            "id": "m-008",
            "name": "안양미용실",
            "category": "beauty",
            "latitude": 37.3990, "longitude": 126.9280,
            "address": "경기 안양시 만안구 안양로 480",
            "road_address": "경기 안양시 만안구 안양로 480",
            "phone": "031-441-8899",
            "supports_onnuri": False, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["localCurrency", "card"],
            "products": ["커트", "펌", "염색", "매직"],
            "business_hours": {"summary": "화-일 10:00 - 20:00", "closedNote": "월요일 휴무"},
            "rating": 4.6, "review_count": 72,
            "market_name": None,
            "description": "안양 여성 헤어 전문점. 안양사랑페이 결제 시 5% 추가할인.",
            "last_verified_at": _days_ago(3),
            "reviews": [
                {"user_name": "수민", "rating": 5, "content": "안양사랑페이로 결제 잘 됨. 매직 자연스러워요.", "created_at": _days_ago(11), "payment_type": "localCurrency", "payment_verified": True, "purchased_product": "매직"},
            ],
            "recent_payments": [
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(3), "note": None},
            ],
        },
        {
            "id": "m-009",
            "name": "범계문구백화점",
            "category": "life",
            "latitude": 37.3906, "longitude": 126.9755,
            "address": "경기 안양시 동안구 시민대로 190",
            "road_address": "경기 안양시 동안구 시민대로 190",
            "phone": "031-386-5566",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "localCurrency", "card"],
            "products": ["노트", "볼펜", "포장지", "학용품 세트"],
            "business_hours": {"summary": "매일 09:00 - 21:00", "closedNote": None},
            "rating": 4.2, "review_count": 33,
            "market_name": None,
            "description": "학용품, 사무용품 종합 매장.",
            "last_verified_at": _days_ago(9),
            "reviews": [
                {"user_name": "학부모", "rating": 4, "content": "온누리로 학용품 살 수 있어서 편해요.", "created_at": _days_ago(15), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "학용품 세트"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(4), "note": None},
            ],
        },
        {
            "id": "m-010",
            "name": "평촌한우촌",
            "category": "restaurant",
            "latitude": 37.3925, "longitude": 126.9700,
            "address": "경기 안양시 동안구 평촌대로 155",
            "road_address": "경기 안양시 동안구 평촌대로 155",
            "phone": "031-381-2266",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriCard", "localCurrency", "card"],
            "products": ["한우 등심", "한우 채끝", "육회", "냉면"],
            "business_hours": {"summary": "매일 11:30 - 22:00", "closedNote": None},
            "rating": 4.7, "review_count": 187,
            "market_name": None,
            "description": "한우 전문점. 상품권 최대한 활용 가능.",
            "last_verified_at": _days_ago(2),
            "reviews": [
                {"user_name": "가족손님", "rating": 5, "content": "한우 회식 온누리 카드형으로 결제 완료. 서비스 훌륭.", "created_at": _days_ago(3), "payment_type": "onnuriCard", "payment_verified": True, "purchased_product": "한우 등심"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriCard", "succeeded_at": _days_ago(0), "note": "한우 등심 400g"},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(6), "note": None},
            ],
        },
        {
            "id": "m-011",
            "name": "청춘꽃집",
            "category": "etc",
            "latitude": 37.3948, "longitude": 126.9245,
            "address": "경기 안양시 만안구 만안로 235 안양중앙시장",
            "road_address": "경기 안양시 만안구 만안로 235",
            "phone": "031-441-9911",
            "supports_onnuri": True, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "card"],
            "products": ["꽃다발", "화분", "졸업식 꽃", "생일 꽃"],
            "business_hours": {"summary": "매일 10:00 - 20:00", "closedNote": None},
            "rating": 4.9, "review_count": 96,
            "market_name": "안양중앙시장",
            "description": "청년 사장님이 운영하는 감성 꽃집.",
            "last_verified_at": _days_ago(2),
            "reviews": [
                {"user_name": "지환", "rating": 5, "content": "온누리로 꽃다발 결제 잘 됩니다.", "created_at": _days_ago(1), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "꽃다발"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(1), "note": None},
            ],
        },
        {
            "id": "m-012",
            "name": "평촌우리제과",
            "category": "cafe",
            "latitude": 37.3900, "longitude": 126.9680,
            "address": "경기 안양시 동안구 평촌대로 100",
            "road_address": "경기 안양시 동안구 평촌대로 100",
            "phone": "031-381-5544",
            "supports_onnuri": False, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["localCurrency", "card"],
            "products": ["식빵", "크루아상", "생크림 케이크", "단팥빵"],
            "business_hours": {"summary": "매일 07:00 - 22:00", "closedNote": None},
            "rating": 4.5, "review_count": 121,
            "market_name": None,
            "description": "동네 인기 베이커리.",
            "last_verified_at": _days_ago(4),
            "reviews": [
                {"user_name": "재원", "rating": 5, "content": "안양사랑페이로 케이크 결제 완료. 부드러워요.", "created_at": _days_ago(5), "payment_type": "localCurrency", "payment_verified": True, "purchased_product": "생크림 케이크"},
            ],
            "recent_payments": [
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(2), "note": None},
            ],
        },
        {
            "id": "m-013",
            "name": "관양동 새마을수퍼",
            "category": "mart",
            "latitude": 37.3982, "longitude": 126.9724,
            "address": "경기 안양시 동안구 관양로 88",
            "road_address": "경기 안양시 동안구 관양로 88",
            "phone": "031-421-3311",
            "supports_onnuri": True, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "card"],
            "products": ["과자", "음료", "생수", "라면", "간편식"],
            "business_hours": {"summary": "매일 06:30 - 24:00", "closedNote": None},
            "rating": 4.1, "review_count": 41,
            "market_name": None,
            "description": "24시간 가까이 여는 동네 수퍼.",
            "last_verified_at": _days_ago(7),
            "reviews": [],
            "recent_payments": [
                {"payment_type": "onnuriPaper", "succeeded_at": _days_ago(5), "note": None},
            ],
        },
        {
            "id": "m-014",
            "name": "안양중앙시장 옛날통닭",
            "category": "restaurant",
            "latitude": 37.3944, "longitude": 126.9238,
            "address": "경기 안양시 만안구 만안로 232 안양중앙시장",
            "road_address": "경기 안양시 만안구 만안로 232",
            "phone": "031-441-4444",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "localCurrency", "card"],
            "products": ["옛날통닭", "간장치킨", "닭강정"],
            "business_hours": {"summary": "화-일 12:00 - 22:00", "closedNote": "월요일 휴무"},
            "rating": 4.6, "review_count": 205,
            "market_name": "안양중앙시장",
            "description": "가마솥에 튀기는 옛날통닭.",
            "last_verified_at": _days_ago(1),
            "reviews": [
                {"user_name": "동네주민", "rating": 5, "content": "온누리로 통닭 사먹는 재미. 바삭!", "created_at": _days_ago(2), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "옛날통닭"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(0), "note": None},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(4), "note": None},
            ],
        },
        {
            "id": "m-015",
            "name": "시청역안경원",
            "category": "life",
            "latitude": 37.3940, "longitude": 126.9565,
            "address": "경기 안양시 동안구 시민대로 235",
            "road_address": "경기 안양시 동안구 시민대로 235",
            "phone": "031-386-7070",
            "supports_onnuri": False, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["localCurrency", "card"],
            "products": ["안경테", "선글라스", "렌즈"],
            "business_hours": {"summary": "월-토 10:00 - 20:00", "closedNote": "일요일 휴무"},
            "rating": 4.4, "review_count": 58,
            "market_name": None,
            "description": "정확한 시력측정과 안양사랑페이 결제 지원.",
            "last_verified_at": _days_ago(5),
            "reviews": [],
            "recent_payments": [
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(7), "note": None},
            ],
        },
        {
            "id": "m-016",
            "name": "평촌스터디카페",
            "category": "cafe",
            "latitude": 37.3910, "longitude": 126.9720,
            "address": "경기 안양시 동안구 시민대로 200",
            "road_address": "경기 안양시 동안구 시민대로 200",
            "phone": "031-381-9090",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "localCurrency", "card", "qr"],
            "products": ["시간권", "정기권", "음료"],
            "business_hours": {"summary": "24시간", "closedNote": None},
            "rating": 4.3, "review_count": 78,
            "market_name": None,
            "description": "24시간 무인 스터디카페.",
            "last_verified_at": _days_ago(3),
            "reviews": [
                {"user_name": "수험생", "rating": 4, "content": "정기권 결제 온누리 됨. 조용해요.", "created_at": _days_ago(8), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "정기권"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(3), "note": None},
            ],
        },
        {
            "id": "m-017",
            "name": "안양농협 하나로마트",
            "category": "mart",
            "latitude": 37.3960, "longitude": 126.9550,
            "address": "경기 안양시 만안구 삼덕로 45",
            "road_address": "경기 안양시 만안구 삼덕로 45",
            "phone": "031-441-6666",
            "supports_onnuri": False, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["card", "qr"],
            "products": ["과일", "채소", "쌀", "정육"],
            "business_hours": {"summary": "매일 09:00 - 22:00", "closedNote": None},
            "rating": 4.0, "review_count": 24,
            "market_name": None,
            "description": "일반 카드 및 페이 사용 가능. 상품권은 미사용.",
            "last_verified_at": _days_ago(12),
            "reviews": [],
            "recent_payments": [],
        },
        {
            "id": "m-018",
            "name": "안양대박곱창",
            "category": "restaurant",
            "latitude": 37.3935, "longitude": 126.9585,
            "address": "경기 안양시 만안구 안양로 250",
            "road_address": "경기 안양시 만안구 안양로 250",
            "phone": "031-441-8282",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriCard", "localCurrency", "card"],
            "products": ["소곱창", "대창", "막창", "볶음밥"],
            "business_hours": {"summary": "매일 16:00 - 24:00", "closedNote": None},
            "rating": 4.6, "review_count": 168,
            "market_name": None,
            "description": "숯불곱창 전문점. 상품권 활용도 최고.",
            "last_verified_at": _days_ago(2),
            "reviews": [
                {"user_name": "회식러", "rating": 5, "content": "회식 4명 온누리·안양페이 조합 결제 성공.", "created_at": _days_ago(3), "payment_type": "onnuriCard", "payment_verified": True, "purchased_product": "소곱창"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriCard", "succeeded_at": _days_ago(1), "note": None},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(5), "note": None},
            ],
        },
        {
            "id": "m-019",
            "name": "옹기떡집",
            "category": "food",
            "latitude": 37.3988, "longitude": 126.9738,
            "address": "경기 안양시 동안구 관평로 210",
            "road_address": "경기 안양시 동안구 관평로 210",
            "phone": "031-421-5544",
            "supports_onnuri": True, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "card"],
            "products": ["백설기", "인절미", "떡국떡", "꿀떡"],
            "business_hours": {"summary": "월-토 07:00 - 20:00", "closedNote": "일요일 휴무"},
            "rating": 4.7, "review_count": 88,
            "market_name": "관양시장",
            "description": "3대째 이어온 방앗간.",
            "last_verified_at": _days_ago(4),
            "reviews": [
                {"user_name": "떡순이", "rating": 5, "content": "지류 온누리도 잘 받아주십니다.", "created_at": _days_ago(6), "payment_type": "onnuriPaper", "payment_verified": True, "purchased_product": "인절미"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(2), "note": None},
            ],
        },
        {
            "id": "m-020",
            "name": "인덕원카페 라온",
            "category": "cafe",
            "latitude": 37.4010, "longitude": 126.9770,
            "address": "경기 안양시 동안구 관평로 292",
            "road_address": "경기 안양시 동안구 관평로 292",
            "phone": "031-421-7777",
            "supports_onnuri": False, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["localCurrency", "card", "qr"],
            "products": ["드립커피", "치즈케이크", "레몬에이드"],
            "business_hours": {"summary": "화-일 10:00 - 22:00", "closedNote": "월요일 휴무"},
            "rating": 4.7, "review_count": 143,
            "market_name": None,
            "description": "인덕원 감성 카페.",
            "last_verified_at": _days_ago(3),
            "reviews": [],
            "recent_payments": [
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(4), "note": None},
            ],
        },
        {
            "id": "m-021",
            "name": "안양중앙시장 반찬왕",
            "category": "food",
            "latitude": 37.3953, "longitude": 126.9242,
            "address": "경기 안양시 만안구 만안로 234",
            "road_address": "경기 안양시 만안구 만안로 234",
            "phone": "031-441-7373",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "localCurrency", "card"],
            "products": ["오이무침", "김치", "젓갈", "장아찌"],
            "business_hours": {"summary": "매일 09:00 - 20:00", "closedNote": None},
            "rating": 4.5, "review_count": 66,
            "market_name": "안양중앙시장",
            "description": "반찬 종류만 30가지.",
            "last_verified_at": _days_ago(2),
            "reviews": [],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(1), "note": None},
            ],
        },
        {
            "id": "m-022",
            "name": "동네정직세탁소",
            "category": "life",
            "latitude": 37.3975, "longitude": 126.9600,
            "address": "경기 안양시 만안구 만안로 130",
            "road_address": "경기 안양시 만안구 만안로 130",
            "phone": "031-441-2323",
            "supports_onnuri": False, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["localCurrency", "card"],
            "products": ["정장 드라이", "코트 드라이", "이불 세탁"],
            "business_hours": {"summary": "월-토 08:00 - 20:00", "closedNote": "일요일 휴무"},
            "rating": 4.3, "review_count": 21,
            "market_name": None,
            "description": "동네 세탁소. 안양사랑페이 결제 가능.",
            "last_verified_at": _days_ago(8),
            "reviews": [],
            "recent_payments": [
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(6), "note": None},
            ],
        },
        {
            "id": "m-023",
            "name": "평촌족발",
            "category": "restaurant",
            "latitude": 37.3908, "longitude": 126.9705,
            "address": "경기 안양시 동안구 평촌대로 160",
            "road_address": "경기 안양시 동안구 평촌대로 160",
            "phone": "031-381-6262",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "localCurrency", "card"],
            "products": ["족발", "보쌈", "쟁반국수"],
            "business_hours": {"summary": "매일 15:00 - 24:00", "closedNote": None},
            "rating": 4.5, "review_count": 132,
            "market_name": None,
            "description": "야식 명소.",
            "last_verified_at": _days_ago(2),
            "reviews": [
                {"user_name": "야식러", "rating": 5, "content": "온누리로 족발 결제. 배달 X, 방문 O.", "created_at": _days_ago(4), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "족발"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(1), "note": None},
            ],
        },
        {
            "id": "m-024",
            "name": "중앙시장 계절과일",
            "category": "food",
            "latitude": 37.3950, "longitude": 126.9237,
            "address": "경기 안양시 만안구 만안로 233",
            "road_address": "경기 안양시 만안구 만안로 233",
            "phone": "031-441-1919",
            "supports_onnuri": True, "supports_local_currency": True,
            "local_currency_name": "안양사랑페이",
            "supported_payment_types": ["onnuriDigital", "onnuriPaper", "localCurrency", "card"],
            "products": ["사과", "귤", "포도", "복숭아", "선물세트"],
            "business_hours": {"summary": "매일 08:00 - 21:00", "closedNote": None},
            "rating": 4.6, "review_count": 74,
            "market_name": "안양중앙시장",
            "description": "제철 과일 전문.",
            "last_verified_at": _days_ago(1),
            "reviews": [
                {"user_name": "과일러버", "rating": 5, "content": "온누리로 사과 한 박스 결제. 달아요.", "created_at": _days_ago(2), "payment_type": "onnuriDigital", "payment_verified": True, "purchased_product": "사과"},
            ],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(0), "note": "사과 1박스"},
                {"payment_type": "localCurrency", "succeeded_at": _days_ago(5), "note": None},
            ],
        },
        {
            "id": "m-025",
            "name": "헤어살롱 준",
            "category": "beauty",
            "latitude": 37.3928, "longitude": 126.9575,
            "address": "경기 안양시 만안구 안양로 300",
            "road_address": "경기 안양시 만안구 안양로 300",
            "phone": "031-441-5959",
            "supports_onnuri": True, "supports_local_currency": False,
            "local_currency_name": None,
            "supported_payment_types": ["onnuriDigital", "onnuriCard", "card"],
            "products": ["남성 커트", "여성 커트", "베이직 펌"],
            "business_hours": {"summary": "화-일 10:30 - 20:00", "closedNote": "월요일 휴무"},
            "rating": 4.4, "review_count": 45,
            "market_name": None,
            "description": "가족 단위 손님 많은 미용실.",
            "last_verified_at": _days_ago(6),
            "reviews": [],
            "recent_payments": [
                {"payment_type": "onnuriDigital", "succeeded_at": _days_ago(4), "note": None},
            ],
        },
    ]
